<?php
// $Id: qq_login.info,v 0.1 20110603 Felix $

/**
 * @file
 * 实现QQ用户共享登录
 */

/**
 * Implementation of hook_menu.
 */
function qq_login_menu() {
  
  $items['qq/login'] = array(
    'description' => 'QQ用户登录或者绑定',
    'page callback' => 'qq_login_page_login',
    'access callback' => 'user_is_anonymous',
    'type' => MENU_CALLBACK,
    'file' => 'qq_login.pages.inc',
  );
  $items['qq/callback'] = array(
    'title' => 'QQ共享登录页面跳转同步通知路径',
    'page callback' => 'qq_login_page_callback',
    'access callback' => 'user_is_anonymous',
    'type' => MENU_CALLBACK,
    'file' => 'qq_login.pages.inc',
  );
  $items['admin/settings/band/qq'] = array(
    'title' => 'QQ共享登录',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('qq_login_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'qq_login.admin.inc',
  );
  
  return $items;
}

function qq_login_get_config(){
	$qq_config['app_id'] = variable_get('qq_login_app_id', NULL);
	$qq_config['app_key'] = variable_get('qq_login_app_key', NULL);
	$qq_config['return_url'] = 'http://'.$_SERVER['HTTP_HOST'].'/qq/callback';

	return $qq_config;
}

/**
 * 使用QQ帐号登录或绑定帐号的权限
 */
function qq_login_is_access() {
  global $user;
  return $user->uid > 0 || variable_get('qq_login_is_login', 1);
}

/**
 * Implementation of hook_form_alter
 */
function qq_login_form_alter(&$form, $form_state, $form_id) {
  if (variable_get('qq_login_is_login', 1) && ($form_id == 'user_login_block' || $form_id == 'user_login')) {
    $form['qq_login_button'] = array(
      '#type' => 'item',
      '#value' => qq_login_render_button(),
      '#weight' => 10,
    );
  }
  return $form;
}

function qq_login_render_button(){
	$html = '<a href="/qq/login" alt="使用QQ帐号登录"><img width=159 height=33 src="qq_login.png"></a>';
	return $html;
}

/**
 * @Implement of hook_user()
 */
function qq_login_user($op, &$edit, &$account, $category = NULL) {
  switch ($op) {
    case 'delete':
      db_query("DELETE FROM {user_band_user} WHERE uid = %d AND thirdpart_type = 'qq'", $account->uid);
    break;   
  }
}