<?php
/**
 * Implementation of hook_form_alter(). 
 * @Where sina_open_set_tweet_form in sina_open.module
 * @Do before set_tweet ,insert into our Additional db_table sina_weibo2node info.
 */
function user_rigester_alter_form_alter(&$form, $form_state, $form_id) {
	if(($form_id == 'user_register')){
		unset($form['name']['#description']);
		unset($form['mail']['#description']);
	}if(($form_id == 'user_login')){
		unset($form['name']['#description']);
		unset($form['pass']['#description']);
	}
	
  return $form;
}
function get_least_node2weibo($counts=5){
	$sql="SELECT *
			FROM sina_weibo2node
			ORDER BY created_at DESC
			LIMIT 0 , $counts";
	$results =db_query($sql);
	foreach($results as $key){
		$objs[]=db_fetch_object($results)->data;//json_decode
	}
	if(function_exists(dpm)) dpm($objs);
	return $objs;
}
/**
 * @} End of "defgroup page_example".
 */

 