<?php
// $Id: tuan800_login.info,v 0.1 20110523 Felix $

/**
 * @file
 * 实现团800用户共享登录
 */

/**
 * Implementation of hook_menu.
 */
function tuan800_login_menu() {
  
  $items['tuan800/login'] = array(
    'description' => '团800用户登录或者绑定',
    'page callback' => 'tuan800_login_page_login',
    'access callback' => 'user_is_anonymous',
    'type' => MENU_CALLBACK,
    'file' => 'tuan800_login.pages.inc',
  );
  $items['tuan800/callback'] = array(
    'title' => '团800共享登录页面跳转同步通知路径',
    'page callback' => 'tuan800_login_page_callback',
    'access callback' => 'user_is_anonymous',
    'type' => MENU_CALLBACK,
    'file' => 'tuan800_login.pages.inc',
  );
  $items['admin/settings/band/tuan800'] = array(
    'title' => '团800共享登录',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tuan800_login_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'tuan800_login.admin.inc',
  );
  
  return $items;
}

function tuan800_login_get_config(){
	$tuan800_config['app_key'] = variable_get('tuan800_login_app_key', NULL);
	$tuan800_config['app_secret'] = variable_get('tuan800_login_app_secret', NULL);
	$tuan800_config['auto_email'] = variable_get('tuan800_login_auto_email', 1);
	$tuan800_config['return_url'] = 'http://'.$_SERVER['HTTP_HOST'].'/tuan800/callback';

	return $tuan800_config;
}

/**
 * 使用团800帐号登录或绑定帐号的权限
 */
function tuan800_login_is_access() {
  global $user;
  return $user->uid > 0 || variable_get('tuan800_login_is_login', 1);
}

/**
 * Implementation of hook_form_alter
 */
function tuan800_login_form_alter(&$form, $form_state, $form_id) {
  if (variable_get('tuan800_login_is_login', 1) && ($form_id == 'user_login_block' || $form_id == 'user_login')) {
    $form['tuan800_login_button'] = array(
      '#type' => 'item',
      '#value' => tuan800_login_render_button(),
      '#weight' => 14,
    );
  }
  return $form;
}

function tuan800_login_render_button(){
	$html = '<a href="/tuan800/login" alt="使用团800帐号登录"><img src="/sites/all/modules/user_band/images/tuan800_login.png"></a>';
	return $html;
}

/**
 * @Implement of hook_user()
 */
function tuan800_login_user($op, &$edit, &$account, $category = NULL) {
  switch ($op) {
    case 'delete':
      db_query("DELETE FROM {user_band_user} WHERE uid = %d AND thirdpart_type = 'tuan800'", $account->uid);
    break;   
  }
}

function tuan800_login_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  $tuan800_config = tuan800_login_get_config();
  if (!user_is_anonymous()) return; // Only process for anonymous users.	
  if (_uc_deal_is_uc_type($node->type)) {
    if (($op === 'view')&&($_POST['from']==='tuan800')) {
      //var_dump($_SESSION);
      $qid   = $_POST['qid'];
	  $qname = urldecode($_POST['qname']);
      $qmail = urldecode($_POST['qmail']);
      $from  = $_POST['from'];
      $sign  = $_POST['sign'];
      $key = $tuan800_config['app_key'];
      $secret = $tuan800_config['app_secret'];
      $sign_cal = md5($qid.'|'.$qname.'|'.$qmail.'|'.$from.'|'.$key.'|'.$secret);

      // Log the user in if signs match.
      if ($sign_cal == $sign) {
      	$ouser = array(
			'ouid'=> $qname,
			'name'=> $qname,
			//'token' => $token,
			'from'=>'tuan800',
			);
		if($tuan800_config['auto_email']){  //自动生成Email
			$ouser['email'] = $qname.'@tuan800.com';
		}
		user_band_bandapi($ouser,false);
	  }
    }
  }
}


