<?php
/**
 * @author dale
 * @version $Id$
 * @copyright dale
 * @package sina
 */
function sina_vp_imagetool_init(){
	//仿新浪图片放大，反转方式。
	//drupal_add_css(drupal_get_path('module', 'sina_vp_imagetool') .'/css/sina_vp_imagetool.css');
	//drupal_add_js(drupal_get_path('module', 'sina_vp_imagetool') .'/js/sina_vp_imagetool.js');
	drupal_add_css(drupal_get_path('theme', 'vp').'/dialog.css');
	drupal_add_js(drupal_get_path('theme', 'vp').'/dialog.js');
	
	//drupal_add_js(drupal_get_path('module', 'sina_vp_imagetool') .'/js/jquery-1.7.1.js');
	drupal_add_js(drupal_get_path('module', 'sina_vp_imagetool') .'/js/jquery.lazyload.min.js');
	drupal_add_js(drupal_get_path('module', 'sina_vp_imagetool') .'/js/jquery.lazyload-extra.js');
	drupal_add_css(drupal_get_path('module', 'sina_vp_imagetool').'/css/izhuanjiao.css');
	drupal_add_js(drupal_get_path('module', 'sina_vp_imagetool').'/js/izhuanjiao.js');	
	drupal_add_js(drupal_get_path('module', 'sina_vp_imagetool').'/js/likeload.js');	
}

/**
 * 添加一个imageCache 微博头像 50X 150X 180X
 * HOOK_imagecache_default_presets()
 */
function sina_vp_imagetool_imagecache_default_presets(){
  $presets = array();
  $presets['35x35'] = array ( //头像
    'presetname' => '35x35',
    'actions' => array (
      0 => array (
        'weight' => '0',
        'module' => 'imagecache',
        'action' => 'imagecache_scale',
        'data' => array (
          'width' => '35',
          'height' => '35',
        ),
      ), 
      1 => array (//radius: 0.5, sigma: 0.5, amount: 100, threshold: 0.05
        'weight' => '1',
        'module' => 'imagecache',
        'action' => 'imagecache_sharpen',
        'data' => array (
          'radius' => '0.5',
          'sigma' => '0.5',
          'amount' => '100',
          'threshold' => '00.5',
        ),
      ),
    ),
  );
	$presets['50x50'] = array ( //头像
    'presetname' => '50x50',
    'actions' => array (
      0 => array (
        'weight' => '0',
        'module' => 'imagecache',
        'action' => 'imagecache_scale',
        'data' => array (
          'width' => '50',
          'height' => '50',
        ),
      ), 
      1 => array (//radius: 0.5, sigma: 0.5, amount: 100, threshold: 0.05
        'weight' => '1',
        'module' => 'imagecache',
        'action' => 'imagecache_sharpen',
        'data' => array (
          'radius' => '0.5',
          'sigma' => '0.5',
          'amount' => '100',
          'threshold' => '00.5',
        ),
      ),
    ),
  );
	$presets['65x65'] = array ( //头像
    'presetname' => '65x65',
    'actions' => array (
      0 => array (
        'weight' => '0',
        'module' => 'imagecache',
        'action' => 'imagecache_scale',
        'data' => array (
          'width' => '65',
          'height' => '65',
        ),
      ), 
      1 => array (//radius: 0.5, sigma: 0.5, amount: 100, threshold: 0.05
        'weight' => '1',
        'module' => 'imagecache',
        'action' => 'imagecache_sharpen',
        'data' => array (
          'radius' => '0.5',
          'sigma' => '0.5',
          'amount' => '100',
          'threshold' => '00.5',
        ),
      ),
    ),
  );
	$presets['w150'] = array (
    'presetname' => 'w150',
    'actions' => array (
      0 => array (
        'weight' => '0',
        'module' => 'imagecache',
        'action' => 'imagecache_scale',
        'data' => array (
          'width' => '150',
          'height' => '100%',
        ),
      ), 
      1 => array (
        'weight' => '1',
        'module' => 'imagecache',
        'action' => 'imagecache_sharpen',
        'data' => array (
          'radius' => '0.5',
          'sigma' => '0.5',
          'amount' => '100',
          'threshold' => '00.5',
        ),
      ),
    ),
  );
	$presets['w200'] = array ( //头像
    'presetname' => 'w200',
    'actions' => array (
      0 => array (
        'weight' => '0',
        'module' => 'imagecache',
        'action' => 'imagecache_scale',
        'data' => array (
          'width' => '200',
          'height' => '100%',
        ),
      ), 
      1 => array (//radius: 0.5, sigma: 0.5, amount: 100, threshold: 0.05
        'weight' => '1',
        'module' => 'imagecache',
        'action' => 'imagecache_sharpen',
        'data' => array (
          'radius' => '0.5',
          'sigma' => '0.5',
          'amount' => '100',
          'threshold' => '00.5',
        ),
      ),
    ),
  );
	$presets['w516'] = array (
    'presetname' => 'w516',
    'actions' => array (
      0 => array (
        'weight' => '0',
        'module' => 'imagecache',
        'action' => 'imagecache_scale',
        'data' => array (
          'width' => '516',
          'height' => '100%',
        ),
      ), 
      1 => array (
        'weight' => '1',
        'module' => 'imagecache',
        'action' => 'imagecache_sharpen',
        'data' => array (
          'radius' => '0.5',
          'sigma' => '0.5',
          'amount' => '100',
          'threshold' => '00.5',
        ),
      ),
    ),
  );
	
  return $presets;
}